create table locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) not null,
    address varchar(255) not null,
    capacity integer not null,
    description varchar(255)
)