create table user_account (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           login varchar(255) not null UNIQUE,
                           password_hash varchar(255) not null,
                           age integer not null check ( age >= 18 ),
                           role varchar(20) not null check ( role in ('ADMIN', 'USER') )
)