create table event_registrations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     event_id BIGINT NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT fk_registration_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_registration_user FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE CASCADE,
                                     CONSTRAINT uk_event_user UNIQUE (event_id, user_id)
)