server:
  port: 8081

spring:
  application:
    name: event-notificator

  datasource:
    url: jdbc:postgresql://localhost:5432/event_notificator
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-notificator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: eventChangeMessage:dev.sorokin.kafka.EventChangeMessage

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO