create table notification_event_payloads (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             message_id UUID NOT NULL UNIQUE,
                                             event_type VARCHAR(50) NOT NULL,
                                             event_id BIGINT NOT NULL,
                                             occurred_at TIMESTAMP NOT NULL,
                                             owner_id BIGINT,
                                             changed_by_id BIGINT,
                                             payload_json JSONB NOT NULL
);