create table notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               payload_id BIGINT NOT NULL,
                               is_read BOOLEAN NOT NULL DEFAULT FALSE,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               read_at TIMESTAMP,
                               CONSTRAINT fk_notification_payload
                                   FOREIGN KEY (payload_id)
                                       REFERENCES notification_event_payloads(id) ON DELETE CASCADE
);